- name: Deploy Angular + Nginx
  hosts: localhost
  become: true
  vars:
    listen_port: 80
    server_name: localhost
    root_path: /usr/share/nginx/html
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove default nginx site
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Copy frontend compiled to Nginx root
      copy:
        src: /app/frontend/dist/frontend/browser/
        dest: "{{ root_path }}/"
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: true

    - name: Deploy nginx site configuration
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Start nginx in foreground (keep container alive)
      command: nginx -g 'daemon off;'

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
